"""Theme definitions - modern inspired dark themes."""

from __future__ import annotations

from typing import Dict


THEMES: Dict[str, Dict[str, str]] = {
    "dark": {
        "name": "Dark",
        "bg": "#1a1d27",
        "bg_secondary": "#1e212f",
        "sidebar_bg": "#12141d",
        "sidebar_hover": "#1c1f2e",
        "sidebar_active": "#252a40",
        "card_bg": "#242836",
        "card_hover": "#2c3044",
        "card_border": "#2f344b",
        "header_bg": "#1e212f",
        "footer_bg": "#1e212f",
        "input_bg": "#1f2333",
        "input_border": "#2f344b",
        "text_primary": "#e6e8f0",
        "text_secondary": "#8b8fa3",
        "text_muted": "#5c5f77",
        "accent": "#e94560",
        "accent_hover": "#ff5a77",
        "accent_active": "#c7364f",
        "accent_secondary": "#2d8cff",
        "success": "#4ade80",
        "warning": "#fbbf24",
        "error": "#f87171",
        "info": "#60a5fa",
        "progress_bg": "#252a3e",
        "progress_fg": "#e94560",
        "scrollbar_bg": "#1a1d27",
        "scrollbar_thumb": "#2f344b",
        "separator": "#252a3e",
        "play_button_bg": "#e94560",
        "play_button_hover": "#ff5a77",
    },
    "midnight": {
        "name": "Midnight",
        "bg": "#10121a",
        "bg_secondary": "#171926",
        "sidebar_bg": "#0b0c14",
        "sidebar_hover": "#151727",
        "sidebar_active": "#1f2236",
        "card_bg": "#191c2a",
        "card_hover": "#222640",
        "card_border": "#23273d",
        "header_bg": "#171926",
        "footer_bg": "#171926",
        "input_bg": "#1a1d2e",
        "input_border": "#252a40",
        "text_primary": "#e2e4f0",
        "text_secondary": "#7d8199",
        "text_muted": "#4e516b",
        "accent": "#7c5cfc",
        "accent_hover": "#9a7cff",
        "accent_active": "#6a4ae0",
        "accent_secondary": "#00d9ff",
        "success": "#4ade80",
        "warning": "#fbbf24",
        "error": "#f87171",
        "info": "#60a5fa",
        "progress_bg": "#1e2030",
        "progress_fg": "#7c5cfc",
        "scrollbar_bg": "#10121a",
        "scrollbar_thumb": "#252a40",
        "separator": "#1e2030",
        "play_button_bg": "#7c5cfc",
        "play_button_hover": "#9a7cff",
    },
    "light": {
        "name": "Light",
        "bg": "#f5f6fa",
        "bg_secondary": "#ffffff",
        "sidebar_bg": "#ebedf3",
        "sidebar_hover": "#e0e3ed",
        "sidebar_active": "#d6dae8",
        "card_bg": "#ffffff",
        "card_hover": "#f8f9ff",
        "card_border": "#e6e8ee",
        "header_bg": "#ffffff",
        "footer_bg": "#ffffff",
        "input_bg": "#ffffff",
        "input_border": "#d0d4e4",
        "text_primary": "#1a1d27",
        "text_secondary": "#5a5e73",
        "text_muted": "#8b8fa3",
        "accent": "#e94560",
        "accent_hover": "#ff5a77",
        "accent_active": "#c7364f",
        "accent_secondary": "#2d8cff",
        "success": "#16a34a",
        "warning": "#d97706",
        "error": "#dc2626",
        "info": "#2563eb",
        "progress_bg": "#e6e8ee",
        "progress_fg": "#e94560",
        "scrollbar_bg": "#f5f6fa",
        "scrollbar_thumb": "#c5cadb",
        "separator": "#e6e8ee",
        "play_button_bg": "#e94560",
        "play_button_hover": "#ff5a77",
    },
    "amoled": {
        "name": "AMOLED",
        "bg": "#000000",
        "bg_secondary": "#0a0a0a",
        "sidebar_bg": "#000000",
        "sidebar_hover": "#141414",
        "sidebar_active": "#1f1f1f",
        "card_bg": "#121212",
        "card_hover": "#1e1e1e",
        "card_border": "#222222",
        "header_bg": "#0a0a0a",
        "footer_bg": "#0a0a0a",
        "input_bg": "#121212",
        "input_border": "#2a2a2a",
        "text_primary": "#ffffff",
        "text_secondary": "#a0a0a0",
        "text_muted": "#606060",
        "accent": "#ff3b5c",
        "accent_hover": "#ff5a77",
        "accent_active": "#e0354f",
        "accent_secondary": "#00d1ff",
        "success": "#4ade80",
        "warning": "#fbbf24",
        "error": "#f87171",
        "info": "#60a5fa",
        "progress_bg": "#1a1a1a",
        "progress_fg": "#ff3b5c",
        "scrollbar_bg": "#000000",
        "scrollbar_thumb": "#2a2a2a",
        "separator": "#1a1a1a",
        "play_button_bg": "#ff3b5c",
        "play_button_hover": "#ff5a77",
    },
}


def get_theme(name: str = "dark") -> Dict[str, str]:
    return THEMES.get(name, THEMES["dark"])


# Common fonts with modern design uses
FONTS = {
    "title": ("Segoe UI", 16, "bold"),
    "title_large": ("Segoe UI", 20, "bold"),
    "heading": ("Segoe UI", 12, "bold"),
    "body": ("Segoe UI", 10),
    "body_bold": ("Segoe UI", 10, "bold"),
    "small": ("Segoe UI", 9),
    "small_bold": ("Segoe UI", 9, "bold"),
    "mono": ("Consolas", 10),
    "mono_small": ("Consolas", 9),
    "icon": ("Segoe UI", 14),
}

# Accent palettes for color picker
ACCENT_PALETTE = [
    "#e94560",
    "#ff3b5c",
    "#ff4655",
    "#00d1ff",
    "#2d8cff",
    "#7c5cfc",
    "#9c27b0",
    "#4caf50",
    "#8bc34a",
    "#ffc107",
    "#ff9800",
    "#ff5722",
    "#00bcd4",
    "#009688",
]
