#!/usr/bin/env bash
# Packages native installers with jpackage (bundled with JDK 17+).
#
# Usage:
#   ./scripts/package.sh                # best bundle for the current OS
#   ./scripts/package.sh app-image      # plain folder with a runnable app
#   ./scripts/package.sh exe            # Windows custom installer (Inno Setup)
#   ./scripts/package.sh msi            # Windows MSI (jpackage + WiX)
#   ./scripts/package.sh dmg            # macOS
#   ./scripts/package.sh deb|rpm        # Linux
#
# Output lands in build/dist/.
set -Eeuo pipefail
trap 'rc=$?; cmd=${BASH_COMMAND:-?}; line=${BASH_LINENO[0]:-0};
      printf "::error::package.sh FAILED rc=%s near line %s: %s\n" "$rc" "$line" "$(printf "%s" "$cmd" | cut -c1-300 | tr ",:" "--")"' ERR
cd "$(dirname "$0")/.."

TYPE="${1:-auto}"

# ---- version from the single source of truth in the source tree
VERSION=$(sed -n 's/.*LAUNCHER_VERSION = "\([^"]*\)".*/\1/p' \
    src/com/omninode/omnilauncher/core/GameLauncher.java | head -1)
if [ -z "$VERSION" ]; then
    echo "error: could not determine LAUNCHER_VERSION from GameLauncher.java" >&2
    exit 1
fi
echo "==> OmniLauncher $VERSION"

# ---- locate jpackage (JDK 17+ ships it; the sandbox JRE does not)
JP="${JPACKAGE:-$(command -v jpackage || true)}"
if [ -z "$JP" ]; then
    for d in "${JAVA_HOME:-}" /usr/lib/jvm/*/ /Library/Java/JavaVirtualMachines/*/Contents/Home; do
        [ -x "${d}bin/jpackage" ] && JP="${d}bin/jpackage" && break
    done
fi
if [ -z "$JP" ]; then
    echo "error: jpackage not found. Install a full JDK 17+ (not a JRE)." >&2
    echo "       (macOS: use a non-JRE build; Windows: Temurin/Adoptium includes it)" >&2
    exit 1
fi

# ---- build the jar and the icons everything needs
./scripts/build.sh
java -jar build/OmniLauncher.jar --export-icon build/icons | sed 's/^/  /'

mkdir -p build/dist
rm -f build/dist/OmniLauncher-* 2>/dev/null || true

OS_NAME="$(uname -s)"
case "$OS_NAME" in
    MINGW*|MSYS*|CYGWIN*|Windows*) OS=windows ;;
    Darwin) OS=macos ;;
    *) OS=linux ;;
esac
if [ "$TYPE" = "auto" ]; then
    case "$OS" in
        windows) TYPE=exe ;;
        macos)   TYPE=dmg ;;
        *)       TYPE=deb ;;
    esac
fi

# macOS bundler rejects app-versions whose first number is 0 (CFBundleVersion
# rule); keep the human version 0.x.y for filenames but use a bundle-legal one
# inside the .app metadata.
JP_VERSION="$VERSION"
if [ "$OS" = macos ]; then
    case "$VERSION" in
        0.*) JP_VERSION="1.${VERSION#0.}" ;;
    esac
fi

COMMON_ARGS=(
    --name OmniLauncher
    --app-version "$JP_VERSION"
    --vendor OmniNodeCo
    --description "Native, dependency-free Minecraft launcher"
    --input build/jpackage-input
    --dest build/dist
)

# stage the jar exactly as jpackage expects (flat input dir)
mkdir -p build/jpackage-input
cp build/OmniLauncher.jar build/jpackage-input/

run_jpackage() {
    local type="$1"
    shift
    echo "==> jpackage --type $type"
    "$JP" --type "$type" ${COMMON_ARGS[@]+"${COMMON_ARGS[@]}"} \
        --main-jar OmniLauncher.jar \
        --main-class com.omninode.omnilauncher.Main \
        "$@"
}

case "$TYPE" in
    app-image)
        run_jpackage app-image
        ;;
    exe)
        # Custom EXE installer: the jpackage app image wrapped with Inno Setup —
        # no MSI/WiX involved. The AppId is fixed, so running a new installer
        # removes the previously installed OmniLauncher first and reinstalls
        # into the same folder; user data lives in %APPDATA%\OmniLauncher and
        # is never touched.
        ICON_ARGS=()
        [ -f build/icons/OmniLauncher.ico ] && ICON_ARGS=(--icon build/icons/OmniLauncher.ico)
        rm -rf build/jpackage-windows
        run_jpackage app-image --dest build/jpackage-windows ${ICON_ARGS[@]+"${ICON_ARGS[@]}"}
        APP_DIR=$(find build/jpackage-windows -maxdepth 1 -type d -name OmniLauncher | head -1)
        [ -n "$APP_DIR" ] || { echo "error: app-image produced no OmniLauncher folder" >&2; exit 1; }
        [ -f build/icons/OmniLauncher.ico ] || { echo "error: build/icons/OmniLauncher.ico missing" >&2; exit 1; }
        ISCC="${INNO_SETUP:-$(command -v ISCC 2>/dev/null || true)}"
        if [ -z "$ISCC" ]; then
            for d in "/c/Program Files (x86)/Inno Setup 6" "/c/Program Files/Inno Setup 6" \
                     "/mnt/c/Program Files (x86)/Inno Setup 6"; do
                [ -f "$d/ISCC.exe" ] && ISCC="$d/ISCC.exe" && break
            done
        fi
        [ -n "$ISCC" ] || { echo "error: Inno Setup 6 not found (set INNO_SETUP or: choco install innosetup)" >&2; exit 1; }
        # Inno resolves paths inside the .iss relative to the .iss location
        # (build/inno), so reference everything as ..\… — no cygpath needed.
        mkdir -p build/inno build/dist
        cat > build/inno/OmniLauncher.iss <<EOF
; Generated by scripts/package.sh — custom OmniLauncher installer (Inno Setup 6)
[Setup]
AppId={{D4A17C50-91A4-4E4D-8F34-7C0A44B62C11}
AppName=OmniLauncher
AppVersion=$VERSION
AppPublisher=OmniNodeCo
AppPublisherURL=https://github.com/OmniNodeCo/OmniLauncher-MC
DefaultDirName={autopf}\OmniLauncher
DefaultGroupName=OmniLauncher
DisableProgramGroupPage=yes
UninstallDisplayIcon={app}\OmniLauncher.exe
OutputDir=..\dist
OutputBaseFilename=OmniLauncher-$VERSION
SetupIconFile=..\icons\OmniLauncher.ico
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64
CloseApplications=yes

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\jpackage-windows\OmniLauncher\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{group}\OmniLauncher"; Filename: "{app}\OmniLauncher.exe"
Name: "{group}\Uninstall OmniLauncher"; Filename: "{uninstallexe}"
Name: "{autodesktop}\OmniLauncher"; Filename: "{app}\OmniLauncher.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\OmniLauncher.exe"; Description: "{cm:LaunchProgram,OmniLauncher}"; Flags: nowait postinstall skipifsilent
EOF
        echo "==> ISCC build/inno/OmniLauncher.iss"
        "$ISCC" "build/inno/OmniLauncher.iss" | sed 's/^/  /'
        ;;
    msi)
        ICON_ARGS=()
        [ -f build/icons/OmniLauncher.ico ] && ICON_ARGS=(--icon build/icons/OmniLauncher.ico)
        run_jpackage msi --win-menu --win-shortcut --win-dir-chooser ${ICON_ARGS[@]+"${ICON_ARGS[@]}"}
        ;;
    dmg)
        # jpackage's DMG bundler (hdiutil + Finder AppleScript) is flaky on CI;
        # build the .app with app-image (embeds the icns), then hdiutil directly.
        ICON_ARGS=()
        [ -f build/icons/OmniLauncher.icns ] && ICON_ARGS=(--icon build/icons/OmniLauncher.icns)
        rm -rf build/mac-app build/mac-dmg
        run_jpackage app-image --dest build/mac-app \
            --mac-package-name OmniLauncher \
            --mac-package-identifier com.omninode.omnilauncher ${ICON_ARGS[@]+"${ICON_ARGS[@]}"}
        APP=$(find build/mac-app -maxdepth 2 -type d -name '*.app' | head -1)
        [ -n "$APP" ] || { echo "error: app-image produced no .app" >&2; exit 1; }
        # Classic drag-to-Applications layout; replacing an old copy keeps all
        # user data (it lives in ~/Library/Application Support/OmniLauncher).
        mkdir -p build/mac-dmg
        mv "$APP" build/mac-dmg/OmniLauncher.app
        cat > build/mac-dmg/"Installation Guide.txt" <<'EOF'
OmniLauncher — installing & upgrading

1. Drag OmniLauncher onto the Applications folder link on the right.
2. If an older copy is already installed, macOS asks whether to replace
   it — choose "Replace". Your accounts, settings and downloaded game
   versions are NOT stored inside the app; they live in
   ~/Library/Application Support/OmniLauncher
   and are kept when you upgrade or remove OmniLauncher.

Uninstalling: drag OmniLauncher from Applications to the Trash.
(Delete the folder above too if you want everything gone.)
EOF
        ln -s /Applications build/mac-dmg/Applications
        hdiutil create -volname OmniLauncher -srcfolder build/mac-dmg \
            -ov -format UDZO build/dist/OmniLauncher-$VERSION.dmg
        ;;
    deb|rpm)
        ICON_ARGS=()
        [ -f build/icons/icon-512.png ] && ICON_ARGS=(--icon build/icons/icon-512.png)
        run_jpackage "$TYPE" --linux-shortcut --linux-menu-group Game \
            --license-file LICENSE ${ICON_ARGS[@]+"${ICON_ARGS[@]}"}
        ;;
    *)
        echo "error: unknown package type '$TYPE'" >&2
        exit 2
        ;;
esac

echo "==> Done — build/dist:"
ls -la build/dist
